# 站点与运行时配置（集中式）
#
# 使用方式：
# 1) 修改本文件的 site 与 runtime/env 配置
# 2) 运行 `make dev` 或 `npm run config`，脚本会：
#    - 生成/覆盖 src/config/site.ts（供应用内导入使用）
#    - 合并生成 .env.local（以本文件的 runtime.env 为准覆盖同名键）
# 3) .env.local 已被忽略，不会提交到 Git
#
# 说明：
# - 以 NEXT_PUBLIC_ 开头的变量为前端可见（public），勿写入敏感信息
# - 其它变量为服务端使用（secret），请妥善保密

site:
  # 基础信息
  name: "xray.top 透视实验室"
  shortName: "xray.top"
  description: "一个现代化、内容驱动的个人主页，集成了博客、项目展示、笔记等功能。"
  # 站点对外访问的完整 URL（用于 Canonical/OG/Sitemap/Robots 等），务必使用 https
  url: "https://xray.top"

  # 作者信息
  author:
    name: "XRAY"
    url: "https://xray.top/about"

  # 社交链接（按需填写）
  social:
    github: "https://github.com/lushi78778"
    twitter: "https://x.com/lushi78778"
    email: "lushi78778@xray.top"

  # 国际化
  locales: ["zh", "en"]
  defaultLocale: "zh"

  # 备案信息（可选）
  record:
    icp:
      number: "粤ICP备12345678号-1"
      url: "https://beian.miit.gov.cn"
    police:
      number: "粤公网安备 44030502000000号"
      url: "https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44030502000000"

# 运行时配置（Makefile 与脚本会读取这些值）
runtime:
  # 本地或容器内访问服务时的主机与端口，仅用于 Makefile 里的工具任务
  host: "localhost"
  port: 3000
  # ISR 按需刷新接口的密钥（/api/revalidate?secret=...），生产环境替换为强随机值
  revalidateSecret: "dev-sec54f2412345678909876543edfty765redfghjiuytredfcvbhjkiuy"
  # 若使用 Plausible 分析，这里填你的站点域名，否则留空不注入脚本
  plausibleDomain: "xray.top"
  # 统一环境变量（生成到 .env.local）
  env:
    # ——— 站点与可见配置（前端可读取，勿存敏感信息） ———
    # 站点对外 URL（默认会取 site.url），用于前端构造链接与 SEO 信息
  # 注意：为避免重复配置，以下变量由单一来源自动生成：
  # - NEXT_PUBLIC_SITE_URL     ← 由 site.url 自动生成
  # - NEXT_PUBLIC_PLAUSIBLE_DOMAIN ← 由 runtime.plausibleDomain 自动生成

    # ——— 邮件发送（Resend）与联系表单 ———
    # Resend API Key（服务端密钥），用于发送邮件（如联系表单/订阅确认）；生产必须配置
    RESEND_API_KEY: "re_VcbvYDia_Nsr3GKs8XwS1tq1fL9GovW7g"
    # 联系表单收件地址（支持多收件人用逗号分隔），例如：me@example.com,other@example.com
    CONTACT_TO_EMAIL: "lushi78778@xray.top"
    # revalidate 接口的密钥由 runtime.revalidateSecret 自动生成到 .env.local

    # ——— Upstash Redis（限流/缓存/存储） ———
    # Upstash REST URL 与 Token，若启用限流/缓存等功能需配置，否则留空
    UPSTASH_REDIS_REST_URL: ""
    UPSTASH_REDIS_REST_TOKEN: ""

    # ——— Giscus 评论系统（GitHub Discussions） ———
    # 仓库（owner/repo）、仓库 ID、分类名、分类 ID；必须成套配置
    NEXT_PUBLIC_GISCUS_REPO: "lushi78778/Index-home"
    NEXT_PUBLIC_GISCUS_REPO_ID: "R_kgDOP1vONA"
    NEXT_PUBLIC_GISCUS_CATEGORY: "Announcements"
    NEXT_PUBLIC_GISCUS_CATEGORY_ID: "DIC_kwDOP1vONM4Cv4hz"

    # ——— Buttondown 邮件订阅 ———
    # Buttondown API Token（服务端密钥），用于订阅/双重确认等；使用该服务时必须配置
    BUTTONDOWN_API_TOKEN: "42898cd5-7ed0-49ea-977b-c21d467630ed"
    # 是否启用双重确认（默认 true），生产环境建议启用
    BUTTONDOWN_DOUBLE_OPT_IN: true
    # 订阅邮件的发件人（显示名 <地址>），例如："XRAY <noreply@example.com>"
    NEWSLETTER_FROM: "XRAY <noreply@xray.top>"
